# Generated by Django 3.1.5 on 2021-01-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_driver', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('type', models.IntegerField()),
                ('plate_num', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharer', models.IntegerField()),
                ('status', models.IntegerField()),
                ('can_share', models.BooleanField(default=True)),
                ('departure_time', models.DateField()),
                ('total_passenger_num', models.IntegerField()),
                ('destination', models.CharField(max_length=200)),
                ('vehicle_type', models.IntegerField()),
                ('special_request', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.driver')),
            ],
        ),
    ]
